{% set name = "robocorp-http" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robocorp_http-{{ version }}.tar.gz
  sha256: c16ca123201d08cc7684b7f2e3dc6208505d2ae0ff240b285a07d37399daaa95

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - robocorp.http
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robocorp/robo/
  summary: Robocorp HTTP library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
